---
- name: add Hashicorp GPG Key
  apt_key:
    url: "{{ boundary_apt_repo }}/gpg"

- name: add Hashicorp repo
  apt_repository:
    repo: "deb [arch=amd64] {{ boundary_apt_repo }} {{ ansible_distribution_release }} main"
    filename: hashicorp
    update_cache: yes

- name: install Boundary
  apt:
    name: "boundary={{ boundary_version }}"
    force: yes
  notify:
    - 'restart boundary-controller daemon'
    - 'restart boundary-worker daemon'
